# Generated by Django 4.1 on 2022-08-10 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GRASS', 'grass'), ('FIRE', 'fire'), ('WATER', 'water'), ('BUG', 'bug'), ('NORMAL', 'normal'), ('POISON', 'poison'), ('ELECTRIC', 'electric'), ('GROUND', 'ground'), ('FAIRY', 'fairy'), ('FIGHTING', 'fighting'), ('PSYCHIC', 'psychic')], default='GRASS', max_length=20)),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.tipo')),
            ],
            options={
                'db_table': 'personajes',
            },
        ),
    ]
